### ISSUE TITLE
Get Discover People

### ISSUE THREAD

**Issue by CoCEmu** [sdkayy/Kek#1]
Hello,
thank you for this project,
i think it will be very useful by a add 2 void
1 find and return Discover People id for follow
2 find new post for like
(if you add one hook like => OnNewPostRecived {you will get 100* in github;)})
again 
thank you :*

**Comment by sdkayy** [comment]
Thanks, will look into this really like the hook idea.

**Comment by sdkayy** [comment]
Just added some code for it, read the readme for a new example.

**Comment by CoCEmu** [comment]
Thank you,
