### ISSUE TITLE
Like Problem

### ISSUE THREAD

**Issue by CoCEmu** [sdkayy/Kek#2]
Hello, i get this error on like a photo

Exception Throw: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Kek.Utils.Post.Like(String pic) in C:\Users\user\Downloads\Compressed\Kek-master\Kek-master\Kek\Utils\Post.cs:line 114

**Comment by sdkayy** [comment]
Okay let me look into it, give me a few hours.

**Comment by sdkayy** [comment]
Should be fixed with [this commit](https://github.com/sdkayy/Kek/commit/fe64b0ce883f42d5731db26f3c5439ac9cb34cb7). Let me know if you have any issues before I close this, thanks.

**Comment by CoCEmu** [comment]
Good
Thank you,
