### ISSUE TITLE
Problem / Please fix

### ISSUE THREAD

**Issue by Lorymi** [sdkayy/Kek#3]
hi
This project source does not work anymore (it not login to account and do not create an account, etc ...)
Please update the project source
Thankful..

**Comment by sdkayy** [comment]
Hey I will look back into it soon, project went dead. Might remake it one day when I find the time

**Comment by Lorymi** [comment]
@sdkayy 
hi.
I'm still waiting 😂😂
Is it possible to work directly with the [API Instagram](https://www.instagram.com/developer/)? in C#
And give it an example?

**Comment by sdkayy** [comment]
@Lorymi Sorry about all that, this was no longer actively supported, be on the look out I may redo this project with in node.js if that'd be helpful.
